// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoCG8Kbhc65e-n2t4JcUuhmvtr9Nr8HU',
    appId: '1:178077896455:web:facf864bad16e34f3d7fa2',
    messagingSenderId: '178077896455',
    projectId: 'freshmind-3de78',
    authDomain: 'freshmind-3de78.firebaseapp.com',
    storageBucket: 'freshmind-3de78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQnPGAbrBbvqwAipz5emcbztwsoab16Q',
    appId: '1:178077896455:android:10c4c1ee2fb6bedf3d7fa2',
    messagingSenderId: '178077896455',
    projectId: 'freshmind-3de78',
    storageBucket: 'freshmind-3de78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CDRvJ9-a-ztTNSGUB8AI3PO8nOJ166E',
    appId: '1:178077896455:ios:e9ab2590242ab7fb3d7fa2',
    messagingSenderId: '178077896455',
    projectId: 'freshmind-3de78',
    storageBucket: 'freshmind-3de78.appspot.com',
    iosClientId: '178077896455-8ascrmt9c6u0otpasdgbue1iagpemntr.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6CDRvJ9-a-ztTNSGUB8AI3PO8nOJ166E',
    appId: '1:178077896455:ios:e9ab2590242ab7fb3d7fa2',
    messagingSenderId: '178077896455',
    projectId: 'freshmind-3de78',
    storageBucket: 'freshmind-3de78.appspot.com',
    iosClientId: '178077896455-8ascrmt9c6u0otpasdgbue1iagpemntr.apps.googleusercontent.com',
    iosBundleId: 'com.example.freshmind',
  );
}
